### ISSUE TITLE
借鉴别人代码的时候 连出处都不标明吗？

### ISSUE THREAD

**Issue by TonyChen56** [codeByDog/pcWechat#1]

**Comment by codeByDog** [comment]
凡是要点脸的都知道  这些是何冲和赵庆明老师教的，你到底诋毁 然后新版收费  还有理了？打着开源期号  招摇撞骗

**Comment by codeByDog** [comment]
既然要开源 就要有开源精神  不要开源到一半有点流量了就搞收费 什么pro版都出来了 @TonyChen56   丢脸不
